name: Update Availability
on:
  push:
    branches:
      - main
    paths:
      - 'models.json'
  repository_dispatch:
    types: [update_availability]

jobs:
  update_availability:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: pnpm/action-setup@v2.0.1
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Run Update Script
        run: pnpm run dev:update

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: 'iamPrompt GH Actions'
          author_email: 'github-actions[bot]@users.noreply.github.com'
          message: '[Schedule] Update availability'
          add: './availability.json'
          pull: '--rebase --autostash'
          push: true
